# Generated by Django 5.1.4 on 2025-02-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_orders_order_date_alter_orders_required_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='brand_id',
            field=models.IntegerField(unique=True),
        ),
    ]
